[phases.setup]
nixPkgs = ["...", "python312", "python312Packages.pip", "python312Packages.pymupdf", "python312Packages.reportlab", "python312Packages.pillow"]

[phases.install]
cmds = ["npm ci --production"]

[start]
cmd = "node server.js"
